import os

import psycopg

DATABASE_HOST = os.environ.get("DATABASE_HOST", "localhost")
DATABASE_PORT = int(os.environ.get("DATABASE_PORT", "5432"))
DATABASE_NAME = os.environ.get("DATABASE_NAME", "acr_dashboard")
DATABASE_USER = os.environ.get("DATABASE_USER")
DATABASE_PASSWORD = os.environ.get("DATABASE_PASSWORD")


def connect():
    if not DATABASE_USER:
        raise RuntimeError(
            "Defina DATABASE_USER e, quando exigido pelo servidor, DATABASE_PASSWORD"
        )
    return psycopg.connect(
        host=DATABASE_HOST,
        port=DATABASE_PORT,
        dbname=DATABASE_NAME,
        user=DATABASE_USER,
        password=DATABASE_PASSWORD,
    )


def ensure_schema(connection):
    connection.execute("""
        CREATE TABLE IF NOT EXISTS groups (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE
        );
        CREATE TABLE IF NOT EXISTS projects (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL REFERENCES groups(id),
            name TEXT NOT NULL,
            clone_url TEXT NOT NULL,
            UNIQUE(group_id, name)
        );
        CREATE TABLE IF NOT EXISTS branches (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            project_id BIGINT NOT NULL REFERENCES projects(id),
            name TEXT NOT NULL,
            UNIQUE(project_id, name)
        );
        CREATE TABLE IF NOT EXISTS issues (
            branch_id BIGINT NOT NULL REFERENCES branches(id),
            issue_id TEXT NOT NULL,
            type TEXT NOT NULL,
            comment TEXT NOT NULL,
            position_json TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            PRIMARY KEY(branch_id, issue_id)
        );
        CREATE TABLE IF NOT EXISTS executions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_name TEXT NOT NULL,
            project_name TEXT NOT NULL,
            branch_name TEXT NOT NULL,
            started_at TIMESTAMPTZ NOT NULL,
            finished_at TIMESTAMPTZ NOT NULL,
            duration_seconds DOUBLE PRECISION NOT NULL,
            status TEXT NOT NULL,
            output TEXT NOT NULL
        );
        """)
